/**
 * ================================================================
 *  DRAFT BOARDS
 * ================================================================
 *  Full draft-pick log per season, from the Draft Recap workbook.
 *  `owners` maps each team name to its owner for that season,
 *  sourced from the Fantasy Matchup Data workbook. Each pick also
 *  carries a `position` (WR/RB/TE/QB/K/DST) used to tint the cell
 *  on the Draft Board page — sourced from Position Ranks.xlsx where
 *  available, filled in by hand for players who were fully dropped
 *  and never re-added (so they never show up in that workbook).
 * ================================================================
 */

const DRAFTS = {
  2025: {
    owners: {
      "Kelce Krushed my Worthy": "Evan Lamb",
      "Bijan al Gaib": "Jack Callahan",
      "Burrow this Chubb in the Brown": "Adam Kahler",
      "I \u2764\ufe0f Adam Schon": "Zack Rollis",
      "Brocklyn Nine-Nine": "Jon Hurlburt",
      "Uncle Lamb's": "Brent Hurlburt",
      "I like to Chase Brown kids": "Austin Gauss",
      "Bill! Bill! Bill! Bill!": "Benjamin Schon",
      "Oh. My. Gosh. Lookit. Her. Bert": "Zach Crook",
      "Mass Laportations": "Adam Schon",
      "Kareem in my Hunt": "Blake Beachnau",
      "Magic in the Hamptons": "Jacob Ayriss",
    },
    picks: [
      { round: 1, pick: 1, player: "Ja'Marr Chase", team: "Kelce Krushed my Worthy", position: "WR" },
      { round: 1, pick: 2, player: "Bijan Robinson", team: "Bijan al Gaib", position: "RB" },
      { round: 1, pick: 3, player: "Justin Jefferson", team: "Burrow this Chubb in the Brown", position: "WR" },
      { round: 1, pick: 4, player: "Saquon Barkley", team: "I \u2764\ufe0f Adam Schon", position: "RB" },
      { round: 1, pick: 5, player: "Jahmyr Gibbs", team: "Brocklyn Nine-Nine", position: "RB" },
      { round: 1, pick: 6, player: "CeeDee Lamb", team: "Uncle Lamb's", position: "WR" },
      { round: 1, pick: 7, player: "Christian McCaffrey", team: "I like to Chase Brown kids", position: "RB" },
      { round: 1, pick: 8, player: "Malik Nabers", team: "Bill! Bill! Bill! Bill!", position: "WR" },
      { round: 1, pick: 9, player: "Puka Nacua", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "WR" },
      { round: 1, pick: 10, player: "Amon-Ra St. Brown", team: "Mass Laportations", position: "WR" },
      { round: 1, pick: 11, player: "De'Von Achane", team: "Kareem in my Hunt", position: "RB" },
      { round: 1, pick: 12, player: "Ashton Jeanty", team: "Magic in the Hamptons", position: "RB" },
      { round: 2, pick: 1, player: "Nico Collins", team: "Magic in the Hamptons", position: "WR" },
      { round: 2, pick: 2, player: "Brian Thomas Jr.", team: "Kareem in my Hunt", position: "WR" },
      { round: 2, pick: 3, player: "Derrick Henry", team: "Mass Laportations", position: "RB" },
      { round: 2, pick: 4, player: "Jonathan Taylor", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "RB" },
      { round: 2, pick: 5, player: "Josh Jacobs", team: "Bill! Bill! Bill! Bill!", position: "RB" },
      { round: 2, pick: 6, player: "Drake London", team: "I like to Chase Brown kids", position: "WR" },
      { round: 2, pick: 7, player: "Trey McBride", team: "Uncle Lamb's", position: "TE" },
      { round: 2, pick: 8, player: "A.J. Brown", team: "Brocklyn Nine-Nine", position: "WR" },
      { round: 2, pick: 9, player: "Tyreek Hill", team: "I \u2764\ufe0f Adam Schon", position: "WR" },
      { round: 2, pick: 10, player: "Chase Brown", team: "Burrow this Chubb in the Brown", position: "RB" },
      { round: 2, pick: 11, player: "Bucky Irving", team: "Bijan al Gaib", position: "RB" },
      { round: 2, pick: 12, player: "James Cook III", team: "Kelce Krushed my Worthy", position: "RB" },
      { round: 3, pick: 1, player: "Ladd McConkey", team: "Kelce Krushed my Worthy", position: "WR" },
      { round: 3, pick: 2, player: "Tee Higgins", team: "Bijan al Gaib", position: "WR" },
      { round: 3, pick: 3, player: "Joe Burrow", team: "Burrow this Chubb in the Brown", position: "QB" },
      { round: 3, pick: 4, player: "Kenneth Walker III", team: "I \u2764\ufe0f Adam Schon", position: "RB" },
      { round: 3, pick: 5, player: "Brock Bowers", team: "Brocklyn Nine-Nine", position: "TE" },
      { round: 3, pick: 6, player: "Kyren Williams", team: "Uncle Lamb's", position: "RB" },
      { round: 3, pick: 7, player: "Josh Allen", team: "I like to Chase Brown kids", position: "QB" },
      { round: 3, pick: 8, player: "Lamar Jackson", team: "Bill! Bill! Bill! Bill!", position: "QB" },
      { round: 3, pick: 9, player: "George Kittle", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "TE" },
      { round: 3, pick: 10, player: "Terry McLaurin", team: "Mass Laportations", position: "WR" },
      { round: 3, pick: 11, player: "Alvin Kamara", team: "Kareem in my Hunt", position: "RB" },
      { round: 3, pick: 12, player: "Jalen Hurts", team: "Magic in the Hamptons", position: "QB" },
      { round: 4, pick: 1, player: "Omarion Hampton", team: "Magic in the Hamptons", position: "RB" },
      { round: 4, pick: 2, player: "Mike Evans", team: "Kareem in my Hunt", position: "WR" },
      { round: 4, pick: 3, player: "Baker Mayfield", team: "Mass Laportations", position: "QB" },
      { round: 4, pick: 4, player: "James Conner", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "RB" },
      { round: 4, pick: 5, player: "Chuba Hubbard", team: "Bill! Bill! Bill! Bill!", position: "RB" },
      { round: 4, pick: 6, player: "Jaxon Smith-Njigba", team: "I like to Chase Brown kids", position: "WR" },
      { round: 4, pick: 7, player: "Jayden Daniels", team: "Uncle Lamb's", position: "QB" },
      { round: 4, pick: 8, player: "Breece Hall", team: "Brocklyn Nine-Nine", position: "RB" },
      { round: 4, pick: 9, player: "David Montgomery", team: "I \u2764\ufe0f Adam Schon", position: "RB" },
      { round: 4, pick: 10, player: "Zay Flowers", team: "Burrow this Chubb in the Brown", position: "WR" },
      { round: 4, pick: 11, player: "Garrett Wilson", team: "Bijan al Gaib", position: "WR" },
      { round: 4, pick: 12, player: "D'Andre Swift", team: "Kelce Krushed my Worthy", position: "RB" },
      { round: 5, pick: 1, player: "Xavier Worthy", team: "Kelce Krushed my Worthy", position: "WR" },
      { round: 5, pick: 2, player: "Marvin Harrison Jr.", team: "Bijan al Gaib", position: "WR" },
      { round: 5, pick: 3, player: "Jameson Williams", team: "Burrow this Chubb in the Brown", position: "WR" },
      { round: 5, pick: 4, player: "Davante Adams", team: "I \u2764\ufe0f Adam Schon", position: "WR" },
      { round: 5, pick: 5, player: "DJ Moore", team: "Brocklyn Nine-Nine", position: "WR" },
      { round: 5, pick: 6, player: "DK Metcalf", team: "Uncle Lamb's", position: "WR" },
      { round: 5, pick: 7, player: "Courtland Sutton", team: "I like to Chase Brown kids", position: "WR" },
      { round: 5, pick: 8, player: "DeVonta Smith", team: "Bill! Bill! Bill! Bill!", position: "WR" },
      { round: 5, pick: 9, player: "Calvin Ridley", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "WR" },
      { round: 5, pick: 10, player: "Jerry Jeudy", team: "Mass Laportations", position: "WR" },
      { round: 5, pick: 11, player: "Jaylen Waddle", team: "Kareem in my Hunt", position: "WR" },
      { round: 5, pick: 12, player: "Tetairoa McMillan", team: "Magic in the Hamptons", position: "WR" },
      { round: 6, pick: 1, player: "George Pickens", team: "Magic in the Hamptons", position: "WR" },
      { round: 6, pick: 2, player: "Patrick Mahomes", team: "Kareem in my Hunt", position: "QB" },
      { round: 6, pick: 3, player: "Sam LaPorta", team: "Mass Laportations", position: "TE" },
      { round: 6, pick: 4, player: "Tony Pollard", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "RB" },
      { round: 6, pick: 5, player: "Rashee Rice", team: "Bill! Bill! Bill! Bill!", position: "WR" },
      { round: 6, pick: 6, player: "TreVeyon Henderson", team: "I like to Chase Brown kids", position: "RB" },
      { round: 6, pick: 7, player: "Aaron Jones Sr.", team: "Uncle Lamb's", position: "RB" },
      { round: 6, pick: 8, player: "Chris Godwin Jr.", team: "Brocklyn Nine-Nine", position: "WR" },
      { round: 6, pick: 9, player: "Travis Kelce", team: "I \u2764\ufe0f Adam Schon", position: "TE" },
      { round: 6, pick: 10, player: "T.J. Hockenson", team: "Burrow this Chubb in the Brown", position: "TE" },
      { round: 6, pick: 11, player: "Isiah Pacheco", team: "Bijan al Gaib", position: "RB" },
      { round: 6, pick: 12, player: "David Njoku", team: "Kelce Krushed my Worthy", position: "TE" },
      { round: 7, pick: 1, player: "RJ Harvey", team: "Kelce Krushed my Worthy", position: "RB" },
      { round: 7, pick: 2, player: "Brock Purdy", team: "Bijan al Gaib", position: "QB" },
      { round: 7, pick: 3, player: "Cooper Kupp", team: "Burrow this Chubb in the Brown", position: "WR" },
      { round: 7, pick: 4, player: "Bo Nix", team: "I \u2764\ufe0f Adam Schon", position: "QB" },
      { round: 7, pick: 5, player: "Kyler Murray", team: "Brocklyn Nine-Nine", position: "QB" },
      { round: 7, pick: 6, player: "Joe Mixon", team: "Uncle Lamb's", position: "RB" },
      { round: 7, pick: 7, player: "Kaleb Johnson", team: "I like to Chase Brown kids", position: "RB" },
      { round: 7, pick: 8, player: "Matthew Golden", team: "Bill! Bill! Bill! Bill!", position: "WR" },
      { round: 7, pick: 9, player: "Justin Herbert", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "QB" },
      { round: 7, pick: 10, player: "Tyrone Tracy Jr.", team: "Mass Laportations", position: "RB" },
      { round: 7, pick: 11, player: "Rome Odunze", team: "Kareem in my Hunt", position: "WR" },
      { round: 7, pick: 12, player: "Stefon Diggs", team: "Magic in the Hamptons", position: "WR" },
      { round: 8, pick: 1, player: "Jakobi Meyers", team: "Magic in the Hamptons", position: "WR" },
      { round: 8, pick: 2, player: "Jaylen Warren", team: "Kareem in my Hunt", position: "RB" },
      { round: 8, pick: 3, player: "Khalil Shakir", team: "Mass Laportations", position: "WR" },
      { round: 8, pick: 4, player: "Deebo Samuel", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "WR" },
      { round: 8, pick: 5, player: "Brian Robinson Jr.", team: "Bill! Bill! Bill! Bill!", position: "RB" },
      { round: 8, pick: 6, player: "Mark Andrews", team: "I like to Chase Brown kids", position: "TE" },
      { round: 8, pick: 7, player: "Travis Hunter", team: "Uncle Lamb's", position: "WR" },
      { round: 8, pick: 8, player: "Chris Olave", team: "Brocklyn Nine-Nine", position: "WR" },
      { round: 8, pick: 9, player: "Keon Coleman", team: "I \u2764\ufe0f Adam Schon", position: "WR" },
      { round: 8, pick: 10, player: "J.K. Dobbins", team: "Burrow this Chubb in the Brown", position: "RB" },
      { round: 8, pick: 11, player: "Evan Engram", team: "Bijan al Gaib", position: "TE" },
      { round: 8, pick: 12, player: "Caleb Williams", team: "Kelce Krushed my Worthy", position: "QB" },
      { round: 9, pick: 1, player: "Jauan Jennings", team: "Kelce Krushed my Worthy", position: "WR" },
      { round: 9, pick: 2, player: "Quinshon Judkins", team: "Bijan al Gaib", position: "RB" },
      { round: 9, pick: 3, player: "Dak Prescott", team: "Burrow this Chubb in the Brown", position: "QB" },
      { round: 9, pick: 4, player: "Michael Pittman Jr.", team: "I \u2764\ufe0f Adam Schon", position: "WR" },
      { round: 9, pick: 5, player: "Cam Skattebo", team: "Brocklyn Nine-Nine", position: "RB" },
      { round: 9, pick: 6, player: "Keenan Allen", team: "Uncle Lamb's", position: "WR" },
      { round: 9, pick: 7, player: "Jordan Addison", team: "I like to Chase Brown kids", position: "WR" },
      { round: 9, pick: 8, player: "Ricky Pearsall", team: "Bill! Bill! Bill! Bill!", position: "WR" },
      { round: 9, pick: 9, player: "Travis Etienne Jr.", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "RB" },
      { round: 9, pick: 10, player: "Darnell Mooney", team: "Mass Laportations", position: "WR" },
      { round: 9, pick: 11, player: "Jayden Reed", team: "Kareem in my Hunt", position: "WR" },
      { round: 9, pick: 12, player: "Jordan Mason", team: "Magic in the Hamptons", position: "RB" },
      { round: 10, pick: 1, player: "Colston Loveland", team: "Magic in the Hamptons", position: "TE" },
      { round: 10, pick: 2, player: "Tyler Warren", team: "Kareem in my Hunt", position: "TE" },
      { round: 10, pick: 3, player: "Dalton Kincaid", team: "Mass Laportations", position: "TE" },
      { round: 10, pick: 4, player: "Emeka Egbuka", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "WR" },
      { round: 10, pick: 5, player: "Tank Bigsby", team: "Bill! Bill! Bill! Bill!", position: "RB" },
      { round: 10, pick: 6, player: "Javonte Williams", team: "I like to Chase Brown kids", position: "RB" },
      { round: 10, pick: 7, player: "Justin Fields", team: "Uncle Lamb's", position: "QB" },
      { round: 10, pick: 8, player: "Rhamondre Stevenson", team: "Brocklyn Nine-Nine", position: "RB" },
      { round: 10, pick: 9, player: "Zach Ertz", team: "I \u2764\ufe0f Adam Schon", position: "TE" },
      { round: 10, pick: 10, player: "Austin Ekeler", team: "Burrow this Chubb in the Brown", position: "RB" },
      { round: 10, pick: 11, player: "Rashid Shaheed", team: "Bijan al Gaib", position: "WR" },
      { round: 10, pick: 12, player: "Rachaad White", team: "Kelce Krushed my Worthy", position: "RB" },
      { round: 11, pick: 1, player: "Josh Downs", team: "Kelce Krushed my Worthy", position: "WR" },
      { round: 11, pick: 2, player: "Jake Bates", team: "Bijan al Gaib", position: "K" },
      { round: 11, pick: 3, player: "Tucker Kraft", team: "Burrow this Chubb in the Brown", position: "TE" },
      { round: 11, pick: 4, player: "Jaydon Blue", team: "I \u2764\ufe0f Adam Schon", position: "RB" },
      { round: 11, pick: 5, player: "Jayden Higgins", team: "Brocklyn Nine-Nine", position: "WR" },
      { round: 11, pick: 6, player: "Adam Thielen", team: "Uncle Lamb's", position: "WR" },
      { round: 11, pick: 7, player: "Cedric Tillman", team: "I like to Chase Brown kids", position: "WR" },
      { round: 11, pick: 8, player: "Dallas Goedert", team: "Bill! Bill! Bill! Bill!", position: "TE" },
      { round: 11, pick: 9, player: "C.J. Stroud", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "QB" },
      { round: 11, pick: 10, player: "Jared Goff", team: "Mass Laportations", position: "QB" },
      { round: 11, pick: 11, player: "Tyjae Spears", team: "Kareem in my Hunt", position: "RB" },
      { round: 11, pick: 12, player: "Zach Charbonnet", team: "Magic in the Hamptons", position: "RB" },
      { round: 12, pick: 1, player: "Drake Maye", team: "Magic in the Hamptons", position: "QB" },
      { round: 12, pick: 2, player: "Rashod Bateman", team: "Kareem in my Hunt", position: "WR" },
      { round: 12, pick: 3, player: "Cameron Dicker", team: "Mass Laportations", position: "K" },
      { round: 12, pick: 4, player: "Jason Sanders", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "K" },
      { round: 12, pick: 5, player: "Brandon Aiyuk", team: "Bill! Bill! Bill! Bill!", position: "WR" },
      { round: 12, pick: 6, player: "J.J. McCarthy", team: "I like to Chase Brown kids", position: "QB" },
      { round: 12, pick: 7, player: "Jake Ferguson", team: "Uncle Lamb's", position: "TE" },
      { round: 12, pick: 8, player: "Jerome Ford", team: "Brocklyn Nine-Nine", position: "RB" },
      { round: 12, pick: 9, player: "Marvin Mims Jr.", team: "I \u2764\ufe0f Adam Schon", position: "WR" },
      { round: 12, pick: 10, player: "Xavier Legette", team: "Burrow this Chubb in the Brown", position: "WR" },
      { round: 12, pick: 11, player: "Hollywood Brown", team: "Bijan al Gaib", position: "WR" },
      { round: 12, pick: 12, player: "Tua Tagovailoa", team: "Kelce Krushed my Worthy", position: "QB" },
      { round: 13, pick: 1, player: "Chase McLaughlin", team: "Kelce Krushed my Worthy", position: "K" },
      { round: 13, pick: 2, player: "Jordan Love", team: "Bijan al Gaib", position: "QB" },
      { round: 13, pick: 3, player: "Steelers D/ST", team: "Burrow this Chubb in the Brown", position: "DST" },
      { round: 13, pick: 4, player: "Trey Benson", team: "I \u2764\ufe0f Adam Schon", position: "RB" },
      { round: 13, pick: 5, player: "Kyle Pitts Sr.", team: "Brocklyn Nine-Nine", position: "TE" },
      { round: 13, pick: 6, player: "Najee Harris", team: "Uncle Lamb's", position: "RB" },
      { round: 13, pick: 7, player: "Broncos D/ST", team: "I like to Chase Brown kids", position: "DST" },
      { round: 13, pick: 8, player: "Texans D/ST", team: "Bill! Bill! Bill! Bill!", position: "DST" },
      { round: 13, pick: 9, player: "Tyler Allgeier", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "RB" },
      { round: 13, pick: 10, player: "Lions D/ST", team: "Mass Laportations", position: "DST" },
      { round: 13, pick: 11, player: "Matthew Stafford", team: "Kareem in my Hunt", position: "QB" },
      { round: 13, pick: 12, player: "Brandon Aubrey", team: "Magic in the Hamptons", position: "K" },
      { round: 14, pick: 1, player: "Braelon Allen", team: "Magic in the Hamptons", position: "RB" },
      { round: 14, pick: 2, player: "Chris Boswell", team: "Kareem in my Hunt", position: "K" },
      { round: 14, pick: 3, player: "Hunter Henry", team: "Mass Laportations", position: "TE" },
      { round: 14, pick: 4, player: "Vikings D/ST", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "DST" },
      { round: 14, pick: 5, player: "Tyler Bass", team: "Bill! Bill! Bill! Bill!", position: "K" },
      { round: 14, pick: 6, player: "Jake Elliott", team: "I like to Chase Brown kids", position: "K" },
      { round: 14, pick: 7, player: "Wan'Dale Robinson", team: "Uncle Lamb's", position: "WR" },
      { round: 14, pick: 8, player: "Ravens D/ST", team: "Brocklyn Nine-Nine", position: "DST" },
      { round: 14, pick: 9, player: "Ka'imi Fairbairn", team: "I \u2764\ufe0f Adam Schon", position: "K" },
      { round: 14, pick: 10, player: "Tyler Loop", team: "Burrow this Chubb in the Brown", position: "K" },
      { round: 14, pick: 11, player: "Seahawks D/ST", team: "Bijan al Gaib", position: "DST" },
      { round: 14, pick: 12, player: "Patriots D/ST", team: "Kelce Krushed my Worthy", position: "DST" },
      { round: 15, pick: 1, player: "Chig Okonkwo", team: "Kelce Krushed my Worthy", position: "TE" },
      { round: 15, pick: 2, player: "Jaylen Wright", team: "Bijan al Gaib", position: "RB" },
      { round: 15, pick: 3, player: "Nick Chubb", team: "Burrow this Chubb in the Brown", position: "RB" },
      { round: 15, pick: 4, player: "Eagles D/ST", team: "I \u2764\ufe0f Adam Schon", position: "DST" },
      { round: 15, pick: 5, player: "Harrison Butker", team: "Brocklyn Nine-Nine", position: "K" },
      { round: 15, pick: 6, player: "Bills D/ST", team: "Uncle Lamb's", position: "DST" },
      { round: 15, pick: 7, player: "Jonnu Smith", team: "I like to Chase Brown kids", position: "TE" },
      { round: 15, pick: 8, player: "Dalton Schultz", team: "Bill! Bill! Bill! Bill!", position: "TE" },
      { round: 15, pick: 9, player: "Christian Kirk", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "WR" },
      { round: 15, pick: 10, player: "DeMario Douglas", team: "Mass Laportations", position: "WR" },
      { round: 15, pick: 11, player: "Buccaneers D/ST", team: "Kareem in my Hunt", position: "DST" },
      { round: 15, pick: 12, player: "Bears D/ST", team: "Magic in the Hamptons", position: "DST" },
      { round: 16, pick: 1, player: "Tre' Harris", team: "Magic in the Hamptons", position: "WR" },
      { round: 16, pick: 2, player: "Kareem Hunt", team: "Kareem in my Hunt", position: "RB" },
      { round: 16, pick: 3, player: "Jack Bech", team: "Mass Laportations", position: "WR" },
      { round: 16, pick: 4, player: "Michael Wilson", team: "Oh. My. Gosh. Lookit. Her. Bert", position: "WR" },
      { round: 16, pick: 5, player: "Trevor Lawrence", team: "Bill! Bill! Bill! Bill!", position: "QB" },
      { round: 16, pick: 6, player: "DeAndre Hopkins", team: "I like to Chase Brown kids", position: "WR" },
      { round: 16, pick: 7, player: "Chad Ryland", team: "Uncle Lamb's", position: "K" },
      { round: 16, pick: 8, player: "Isaac Guerendo", team: "Brocklyn Nine-Nine", position: "RB" },
      { round: 16, pick: 9, player: "Jalen McMillan", team: "I \u2764\ufe0f Adam Schon", position: "WR" },
      { round: 16, pick: 10, player: "Cam Ward", team: "Burrow this Chubb in the Brown", position: "QB" },
      { round: 16, pick: 11, player: "Darren Waller", team: "Bijan al Gaib", position: "TE" },
      { round: 16, pick: 12, player: "Kalif Raymond", team: "Kelce Krushed my Worthy", position: "WR" },
    ],
  },
  2024: {
    owners: {
      "Beats By Ray (Rice)": "Austin Gauss",
      "I Can't Brees \u270a\ud83c\udfff": "Adam Schon",
      "King Beef": "Evan Lamb",
      "Baby Mama U": "Brent Hurlburt",
      "Commissioner of The Year \ud83d\udc8d": "Jon Hurlburt",
      "Chasing Contracts": "Jack Callahan",
      "Obi-Jan Kenobi": "Jacob Ayriss",
      "Like a good Nabers": "Benjamin Schon",
      "Team Crook": "Zach Crook",
      "Saquon Deez Nuts": "Adam Kahler",
      "Richmond Diamond Dogs": "Zack Rollis",
      "Steeler Virginity": "Blake Beachnau",
    },
    picks: [
      { round: 1, pick: 1, player: "Christian McCaffrey", team: "Beats By Ray (Rice)", position: "RB" },
      { round: 1, pick: 2, player: "CeeDee Lamb", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 1, pick: 3, player: "Amon-Ra St. Brown", team: "King Beef", position: "WR" },
      { round: 1, pick: 4, player: "Tyreek Hill", team: "Baby Mama U", position: "WR" },
      { round: 1, pick: 5, player: "Breece Hall", team: "Commissioner of The Year \ud83d\udc8d", position: "RB" },
      { round: 1, pick: 6, player: "Ja'Marr Chase", team: "Chasing Contracts", position: "WR" },
      { round: 1, pick: 7, player: "Bijan Robinson", team: "Obi-Jan Kenobi", position: "RB" },
      { round: 1, pick: 8, player: "A.J. Brown", team: "Like a good Nabers", position: "WR" },
      { round: 1, pick: 9, player: "Justin Jefferson", team: "Team Crook", position: "WR" },
      { round: 1, pick: 10, player: "Puka Nacua", team: "Saquon Deez Nuts", position: "WR" },
      { round: 1, pick: 11, player: "Jonathan Taylor", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 1, pick: 12, player: "Jahmyr Gibbs", team: "Steeler Virginity", position: "RB" },
      { round: 2, pick: 1, player: "Garrett Wilson", team: "Steeler Virginity", position: "WR" },
      { round: 2, pick: 2, player: "De'Von Achane", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 2, pick: 3, player: "Saquon Barkley", team: "Saquon Deez Nuts", position: "RB" },
      { round: 2, pick: 4, player: "Kyren Williams", team: "Team Crook", position: "RB" },
      { round: 2, pick: 5, player: "Isiah Pacheco", team: "Like a good Nabers", position: "RB" },
      { round: 2, pick: 6, player: "Marvin Harrison Jr.", team: "Obi-Jan Kenobi", position: "WR" },
      { round: 2, pick: 7, player: "Travis Etienne Jr.", team: "Chasing Contracts", position: "RB" },
      { round: 2, pick: 8, player: "Chris Olave", team: "Commissioner of The Year \ud83d\udc8d", position: "WR" },
      { round: 2, pick: 9, player: "Michael Pittman Jr.", team: "Baby Mama U", position: "WR" },
      { round: 2, pick: 10, player: "Nico Collins", team: "King Beef", position: "WR" },
      { round: 2, pick: 11, player: "Derrick Henry", team: "I Can't Brees \u270a\ud83c\udfff", position: "RB" },
      { round: 2, pick: 12, player: "Mike Evans", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 3, pick: 1, player: "Sam LaPorta", team: "Beats By Ray (Rice)", position: "TE" },
      { round: 3, pick: 2, player: "Davante Adams", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 3, pick: 3, player: "Rachaad White", team: "King Beef", position: "RB" },
      { round: 3, pick: 4, player: "Drake London", team: "Baby Mama U", position: "WR" },
      { round: 3, pick: 5, player: "Travis Kelce", team: "Commissioner of The Year \ud83d\udc8d", position: "TE" },
      { round: 3, pick: 6, player: "DK Metcalf", team: "Chasing Contracts", position: "WR" },
      { round: 3, pick: 7, player: "Jaylen Waddle", team: "Obi-Jan Kenobi", position: "WR" },
      { round: 3, pick: 8, player: "Josh Jacobs", team: "Like a good Nabers", position: "RB" },
      { round: 3, pick: 9, player: "Joe Mixon", team: "Team Crook", position: "RB" },
      { round: 3, pick: 10, player: "Brandon Aiyuk", team: "Saquon Deez Nuts", position: "WR" },
      { round: 3, pick: 11, player: "Stefon Diggs", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 3, pick: 12, player: "James Cook", team: "Steeler Virginity", position: "RB" },
      { round: 4, pick: 1, player: "Zay Flowers", team: "Steeler Virginity", position: "WR" },
      { round: 4, pick: 2, player: "DJ Moore", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 4, pick: 3, player: "Kenneth Walker III", team: "Saquon Deez Nuts", position: "RB" },
      { round: 4, pick: 4, player: "Cooper Kupp", team: "Team Crook", position: "WR" },
      { round: 4, pick: 5, player: "Trey McBride", team: "Like a good Nabers", position: "TE" },
      { round: 4, pick: 6, player: "Alvin Kamara", team: "Obi-Jan Kenobi", position: "RB" },
      { round: 4, pick: 7, player: "Josh Allen", team: "Chasing Contracts", position: "QB" },
      { round: 4, pick: 8, player: "Deebo Samuel Sr.", team: "Commissioner of The Year \ud83d\udc8d", position: "WR" },
      { round: 4, pick: 9, player: "Mark Andrews", team: "Baby Mama U", position: "TE" },
      { round: 4, pick: 10, player: "Patrick Mahomes", team: "King Beef", position: "QB" },
      { round: 4, pick: 11, player: "D'Andre Swift", team: "I Can't Brees \u270a\ud83c\udfff", position: "RB" },
      { round: 4, pick: 12, player: "Jalen Hurts", team: "Beats By Ray (Rice)", position: "QB" },
      { round: 5, pick: 1, player: "DeVonta Smith", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 5, pick: 2, player: "George Kittle", team: "I Can't Brees \u270a\ud83c\udfff", position: "TE" },
      { round: 5, pick: 3, player: "Rhamondre Stevenson", team: "King Beef", position: "RB" },
      { round: 5, pick: 4, player: "Lamar Jackson", team: "Baby Mama U", position: "QB" },
      { round: 5, pick: 5, player: "Aaron Jones", team: "Commissioner of The Year \ud83d\udc8d", position: "RB" },
      { round: 5, pick: 6, player: "Calvin Ridley", team: "Chasing Contracts", position: "WR" },
      { round: 5, pick: 7, player: "Dalton Kincaid", team: "Obi-Jan Kenobi", position: "TE" },
      { round: 5, pick: 8, player: "David Montgomery", team: "Like a good Nabers", position: "RB" },
      { round: 5, pick: 9, player: "C.J. Stroud", team: "Team Crook", position: "QB" },
      { round: 5, pick: 10, player: "Joe Burrow", team: "Saquon Deez Nuts", position: "QB" },
      { round: 5, pick: 11, player: "Anthony Richardson", team: "Richmond Diamond Dogs", position: "QB" },
      { round: 5, pick: 12, player: "George Pickens", team: "Steeler Virginity", position: "WR" },
      { round: 6, pick: 1, player: "Amari Cooper", team: "Steeler Virginity", position: "WR" },
      { round: 6, pick: 2, player: "Evan Engram", team: "Richmond Diamond Dogs", position: "TE" },
      { round: 6, pick: 3, player: "Kyle Pitts", team: "Saquon Deez Nuts", position: "TE" },
      { round: 6, pick: 4, player: "James Conner", team: "Team Crook", position: "RB" },
      { round: 6, pick: 5, player: "Malik Nabers", team: "Like a good Nabers", position: "WR" },
      { round: 6, pick: 6, player: "Jonathon Brooks", team: "Obi-Jan Kenobi", position: "RB" },
      { round: 6, pick: 7, player: "Zamir White", team: "Chasing Contracts", position: "RB" },
      { round: 6, pick: 8, player: "Keenan Allen", team: "Commissioner of The Year \ud83d\udc8d", position: "WR" },
      { round: 6, pick: 9, player: "Terry McLaurin", team: "Baby Mama U", position: "WR" },
      { round: 6, pick: 10, player: "Christian Kirk", team: "King Beef", position: "WR" },
      { round: 6, pick: 11, player: "Dak Prescott", team: "I Can't Brees \u270a\ud83c\udfff", position: "QB" },
      { round: 6, pick: 12, player: "Rashee Rice", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 7, pick: 1, player: "Raheem Mostert", team: "Beats By Ray (Rice)", position: "RB" },
      { round: 7, pick: 2, player: "Tank Dell", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 7, pick: 3, player: "Chris Godwin", team: "King Beef", position: "WR" },
      { round: 7, pick: 4, player: "Javonte Williams", team: "Baby Mama U", position: "RB" },
      { round: 7, pick: 5, player: "Tee Higgins", team: "Commissioner of The Year \ud83d\udc8d", position: "WR" },
      { round: 7, pick: 6, player: "David Njoku", team: "Chasing Contracts", position: "TE" },
      { round: 7, pick: 7, player: "Kyler Murray", team: "Obi-Jan Kenobi", position: "QB" },
      { round: 7, pick: 8, player: "Jayden Reed", team: "Like a good Nabers", position: "WR" },
      { round: 7, pick: 9, player: "Christian Watson", team: "Team Crook", position: "WR" },
      { round: 7, pick: 10, player: "Jordan Addison", team: "Saquon Deez Nuts", position: "WR" },
      { round: 7, pick: 11, player: "Keon Coleman", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 7, pick: 12, player: "Jordan Love", team: "Steeler Virginity", position: "QB" },
      { round: 8, pick: 1, player: "Diontae Johnson", team: "Steeler Virginity", position: "WR" },
      { round: 8, pick: 2, player: "Jerome Ford", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 8, pick: 3, player: "Jake Ferguson", team: "Saquon Deez Nuts", position: "TE" },
      { round: 8, pick: 4, player: "Dallas Goedert", team: "Team Crook", position: "TE" },
      { round: 8, pick: 5, player: "Brock Purdy", team: "Like a good Nabers", position: "QB" },
      { round: 8, pick: 6, player: "Tyjae Spears", team: "Obi-Jan Kenobi", position: "RB" },
      { round: 8, pick: 7, player: "Brian Robinson Jr.", team: "Chasing Contracts", position: "RB" },
      { round: 8, pick: 8, player: "Jameson Williams", team: "Commissioner of The Year \ud83d\udc8d", position: "WR" },
      { round: 8, pick: 9, player: "Tony Pollard", team: "Baby Mama U", position: "RB" },
      { round: 8, pick: 10, player: "J.K. Dobbins", team: "King Beef", position: "RB" },
      { round: 8, pick: 11, player: "Austin Ekeler", team: "I Can't Brees \u270a\ud83c\udfff", position: "RB" },
      { round: 8, pick: 12, player: "Courtland Sutton", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 9, pick: 1, player: "Rome Odunze", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 9, pick: 2, player: "Hollywood Brown", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 9, pick: 3, player: "Brock Bowers", team: "King Beef", position: "TE" },
      { round: 9, pick: 4, player: "Jaylen Warren", team: "Baby Mama U", position: "RB" },
      { round: 9, pick: 5, player: "Najee Harris", team: "Commissioner of The Year \ud83d\udc8d", position: "RB" },
      { round: 9, pick: 6, player: "Jaxon Smith-Njigba", team: "Chasing Contracts", position: "WR" },
      { round: 9, pick: 7, player: "Ladd McConkey", team: "Obi-Jan Kenobi", position: "WR" },
      { round: 9, pick: 8, player: "Zach Charbonnet", team: "Like a good Nabers", position: "RB" },
      { round: 9, pick: 9, player: "Ezekiel Elliott", team: "Team Crook", position: "RB" },
      { round: 9, pick: 10, player: "Blake Corum", team: "Saquon Deez Nuts", position: "RB" },
      { round: 9, pick: 11, player: "Curtis Samuel", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 9, pick: 12, player: "Nick Chubb", team: "Steeler Virginity", position: "RB" },
      { round: 10, pick: 1, player: "Zack Moss", team: "Steeler Virginity", position: "RB" },
      { round: 10, pick: 2, player: "Jared Goff", team: "Richmond Diamond Dogs", position: "QB" },
      { round: 10, pick: 3, player: "Xavier Worthy", team: "Saquon Deez Nuts", position: "WR" },
      { round: 10, pick: 4, player: "Tyler Lockett", team: "Team Crook", position: "WR" },
      { round: 10, pick: 5, player: "Khalil Shakir", team: "Like a good Nabers", position: "WR" },
      { round: 10, pick: 6, player: "Brian Thomas Jr.", team: "Obi-Jan Kenobi", position: "WR" },
      { round: 10, pick: 7, player: "Devin Singletary", team: "Chasing Contracts", position: "RB" },
      { round: 10, pick: 8, player: "T.J. Hockenson", team: "Commissioner of The Year \ud83d\udc8d", position: "TE" },
      { round: 10, pick: 9, player: "Chase Brown", team: "Baby Mama U", position: "RB" },
      { round: 10, pick: 10, player: "Darnell Mooney", team: "King Beef", position: "WR" },
      { round: 10, pick: 11, player: "Dalton Schultz", team: "I Can't Brees \u270a\ud83c\udfff", position: "TE" },
      { round: 10, pick: 12, player: "Harrison Butker", team: "Beats By Ray (Rice)", position: "K" },
      { round: 11, pick: 1, player: "Cowboys D/ST", team: "Beats By Ray (Rice)", position: "DST" },
      { round: 11, pick: 2, player: "Gus Edwards", team: "I Can't Brees \u270a\ud83c\udfff", position: "RB" },
      { round: 11, pick: 3, player: "Jaleel McLaughlin", team: "King Beef", position: "RB" },
      { round: 11, pick: 4, player: "DeAndre Hopkins", team: "Baby Mama U", position: "WR" },
      { round: 11, pick: 5, player: "Caleb Williams", team: "Commissioner of The Year \ud83d\udc8d", position: "QB" },
      { round: 11, pick: 6, player: "Jayden Daniels", team: "Chasing Contracts", position: "QB" },
      { round: 11, pick: 7, player: "Brandon Aubrey", team: "Obi-Jan Kenobi", position: "K" },
      { round: 11, pick: 8, player: "Jake Elliott", team: "Like a good Nabers", position: "K" },
      { round: 11, pick: 9, player: "Browns D/ST", team: "Team Crook", position: "DST" },
      { round: 11, pick: 10, player: "49ers D/ST", team: "Saquon Deez Nuts", position: "DST" },
      { round: 11, pick: 11, player: "Justin Tucker", team: "Richmond Diamond Dogs", position: "K" },
      { round: 11, pick: 12, player: "Jerry Jeudy", team: "Steeler Virginity", position: "WR" },
      { round: 12, pick: 1, player: "Rashid Shaheed", team: "Steeler Virginity", position: "WR" },
      { round: 12, pick: 2, player: "Elijah Mitchell", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 12, pick: 3, player: "Jakobi Meyers", team: "Saquon Deez Nuts", position: "WR" },
      { round: 12, pick: 4, player: "Evan McPherson", team: "Team Crook", position: "K" },
      { round: 12, pick: 5, player: "Ravens D/ST", team: "Like a good Nabers", position: "DST" },
      { round: 12, pick: 6, player: "Jets D/ST", team: "Obi-Jan Kenobi", position: "DST" },
      { round: 12, pick: 7, player: "Steelers D/ST", team: "Chasing Contracts", position: "DST" },
      { round: 12, pick: 8, player: "Ty Chandler", team: "Commissioner of The Year \ud83d\udc8d", position: "RB" },
      { round: 12, pick: 9, player: "Kirk Cousins", team: "Baby Mama U", position: "QB" },
      { round: 12, pick: 10, player: "Younghoe Koo", team: "King Beef", position: "K" },
      { round: 12, pick: 11, player: "Jason Myers", team: "I Can't Brees \u270a\ud83c\udfff", position: "K" },
      { round: 12, pick: 12, player: "Brandin Cooks", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 13, pick: 1, player: "Chuba Hubbard", team: "Beats By Ray (Rice)", position: "RB" },
      { round: 13, pick: 2, player: "Bills D/ST", team: "I Can't Brees \u270a\ud83c\udfff", position: "DST" },
      { round: 13, pick: 3, player: "Dolphins D/ST", team: "King Beef", position: "DST" },
      { round: 13, pick: 4, player: "Adam Thielen", team: "Baby Mama U", position: "WR" },
      { round: 13, pick: 5, player: "Aaron Rodgers", team: "Commissioner of The Year \ud83d\udc8d", position: "QB" },
      { round: 13, pick: 6, player: "Greg Zuerlein", team: "Chasing Contracts", position: "K" },
      { round: 13, pick: 7, player: "Trey Benson", team: "Obi-Jan Kenobi", position: "RB" },
      { round: 13, pick: 8, player: "Tua Tagovailoa", team: "Like a good Nabers", position: "QB" },
      { round: 13, pick: 9, player: "Trevor Lawrence", team: "Team Crook", position: "QB" },
      { round: 13, pick: 10, player: "Jake Moody", team: "Saquon Deez Nuts", position: "K" },
      { round: 13, pick: 11, player: "Jaylen Wright", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 13, pick: 12, player: "Pat Freiermuth", team: "Steeler Virginity", position: "TE" },
      { round: 14, pick: 1, player: "Deshaun Watson", team: "Steeler Virginity", position: "QB" },
      { round: 14, pick: 2, player: "Lions D/ST", team: "Richmond Diamond Dogs", position: "DST" },
      { round: 14, pick: 3, player: "Matthew Stafford", team: "Saquon Deez Nuts", position: "QB" },
      { round: 14, pick: 4, player: "Mike Williams", team: "Team Crook", position: "WR" },
      { round: 14, pick: 5, player: "Xavier Legette", team: "Like a good Nabers", position: "WR" },
      { round: 14, pick: 6, player: "Rico Dowdle", team: "Obi-Jan Kenobi", position: "RB" },
      { round: 14, pick: 7, player: "Antonio Gibson", team: "Chasing Contracts", position: "RB" },
      { round: 14, pick: 8, player: "Justin Herbert", team: "Commissioner of The Year \ud83d\udc8d", position: "QB" },
      { round: 14, pick: 9, player: "Joshua Palmer", team: "Baby Mama U", position: "WR" },
      { round: 14, pick: 10, player: "Baker Mayfield", team: "King Beef", position: "QB" },
      { round: 14, pick: 11, player: "Geno Smith", team: "I Can't Brees \u270a\ud83c\udfff", position: "QB" },
      { round: 14, pick: 12, player: "Derek Carr", team: "Beats By Ray (Rice)", position: "QB" },
      { round: 15, pick: 1, player: "Cole Kmet", team: "Beats By Ray (Rice)", position: "TE" },
      { round: 15, pick: 2, player: "Gabe Davis", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 15, pick: 3, player: "Tyler Conklin", team: "King Beef", position: "TE" },
      { round: 15, pick: 4, player: "Saints D/ST", team: "Baby Mama U", position: "DST" },
      { round: 15, pick: 5, player: "Jake Bates", team: "Commissioner of The Year \ud83d\udc8d", position: "K" },
      { round: 15, pick: 6, player: "DeMario Douglas", team: "Chasing Contracts", position: "WR" },
      { round: 15, pick: 7, player: "Dontayvion Wicks", team: "Obi-Jan Kenobi", position: "WR" },
      { round: 15, pick: 8, player: "Romeo Doubs", team: "Like a good Nabers", position: "WR" },
      { round: 15, pick: 9, player: "Tyler Allgeier", team: "Team Crook", position: "RB" },
      { round: 15, pick: 10, player: "Marvin Mims Jr.", team: "Saquon Deez Nuts", position: "WR" },
      { round: 15, pick: 11, player: "Kimani Vidal", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 15, pick: 12, player: "Ka'imi Fairbairn", team: "Steeler Virginity", position: "K" },
      { round: 16, pick: 1, player: "Chiefs D/ST", team: "Steeler Virginity", position: "DST" },
      { round: 16, pick: 2, player: "Tyler Boyd", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 16, pick: 3, player: "Taysom Hill", team: "Saquon Deez Nuts", position: "TE" },
      { round: 16, pick: 4, player: "Kendre Miller", team: "Team Crook", position: "RB" },
      { round: 16, pick: 5, player: "Josh Downs", team: "Like a good Nabers", position: "WR" },
      { round: 16, pick: 6, player: "Adonai Mitchell", team: "Obi-Jan Kenobi", position: "WR" },
      { round: 16, pick: 7, player: "Jahan Dotson", team: "Chasing Contracts", position: "WR" },
      { round: 16, pick: 8, player: "Jaguars D/ST", team: "Commissioner of The Year \ud83d\udc8d", position: "DST" },
      { round: 16, pick: 9, player: "Cairo Santos", team: "Baby Mama U", position: "K" },
      { round: 16, pick: 10, player: "Tyrone Tracy Jr.", team: "King Beef", position: "RB" },
      { round: 16, pick: 11, player: "Kalif Raymond", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 16, pick: 12, player: "Clyde Edwards-Helaire", team: "Beats By Ray (Rice)", position: "RB" },
    ],
  },
  2023: {
    owners: {
      "Beats By Ray (Rice)": "Austin Gauss",
      "Richmond Diamond Dogs": "Zack Rollis",
      "Harbaugh's Burger Joint": "Jacob Ayriss",
      "Commissioner of The Year": "Jon Hurlburt",
      "Team Crook": "Zach Crook",
      "2 Hurlburts 1 Cup": "Brent Hurlburt",
      "I Like Turtles": "Benjamin Schon",
      "I Can't Brees \u270a\ud83c\udfff": "Adam Schon",
      "Saquon these balls": "Jack Callahan",
      "King Beef": "Evan Lamb",
    },
    picks: [
      { round: 1, pick: 1, player: "Justin Jefferson", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 1, pick: 2, player: "Christian McCaffrey", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 1, pick: 3, player: "Ja'Marr Chase", team: "Harbaugh's Burger Joint", position: "WR" },
      { round: 1, pick: 4, player: "Austin Ekeler", team: "Commissioner of The Year", position: "RB" },
      { round: 1, pick: 5, player: "Travis Kelce", team: "Team Crook", position: "TE" },
      { round: 1, pick: 6, player: "Cooper Kupp", team: "2 Hurlburts 1 Cup", position: "WR" },
      { round: 1, pick: 7, player: "Tyreek Hill", team: "I Like Turtles", position: "WR" },
      { round: 1, pick: 8, player: "Derrick Henry", team: "I Can't Brees \u270a\ud83c\udfff", position: "RB" },
      { round: 1, pick: 9, player: "Saquon Barkley", team: "Saquon these balls", position: "RB" },
      { round: 1, pick: 10, player: "Davante Adams", team: "King Beef", position: "WR" },
      { round: 2, pick: 1, player: "Stefon Diggs", team: "King Beef", position: "WR" },
      { round: 2, pick: 2, player: "CeeDee Lamb", team: "Saquon these balls", position: "WR" },
      { round: 2, pick: 3, player: "Bijan Robinson", team: "I Can't Brees \u270a\ud83c\udfff", position: "RB" },
      { round: 2, pick: 4, player: "Nick Chubb", team: "I Like Turtles", position: "RB" },
      { round: 2, pick: 5, player: "Tony Pollard", team: "2 Hurlburts 1 Cup", position: "RB" },
      { round: 2, pick: 6, player: "Josh Jacobs", team: "Team Crook", position: "RB" },
      { round: 2, pick: 7, player: "A.J. Brown", team: "Commissioner of The Year", position: "WR" },
      { round: 2, pick: 8, player: "Chris Olave", team: "Harbaugh's Burger Joint", position: "WR" },
      { round: 2, pick: 9, player: "Tee Higgins", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 2, pick: 10, player: "DeVonta Smith", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 3, pick: 1, player: "Patrick Mahomes", team: "Beats By Ray (Rice)", position: "QB" },
      { round: 3, pick: 2, player: "Josh Allen", team: "Richmond Diamond Dogs", position: "QB" },
      { round: 3, pick: 3, player: "Jalen Hurts", team: "Harbaugh's Burger Joint", position: "QB" },
      { round: 3, pick: 4, player: "Amon-Ra St. Brown", team: "Commissioner of The Year", position: "WR" },
      { round: 3, pick: 5, player: "Garrett Wilson", team: "Team Crook", position: "WR" },
      { round: 3, pick: 6, player: "Joe Mixon", team: "2 Hurlburts 1 Cup", position: "RB" },
      { round: 3, pick: 7, player: "Calvin Ridley", team: "I Like Turtles", position: "WR" },
      { round: 3, pick: 8, player: "DK Metcalf", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 3, pick: 9, player: "Jahmyr Gibbs", team: "Saquon these balls", position: "RB" },
      { round: 3, pick: 10, player: "Travis Etienne Jr.", team: "King Beef", position: "RB" },
      { round: 4, pick: 1, player: "Rhamondre Stevenson", team: "King Beef", position: "RB" },
      { round: 4, pick: 2, player: "Deebo Samuel", team: "Saquon these balls", position: "WR" },
      { round: 4, pick: 3, player: "Joe Burrow", team: "I Can't Brees \u270a\ud83c\udfff", position: "QB" },
      { round: 4, pick: 4, player: "Jonathan Taylor", team: "I Like Turtles", position: "RB" },
      { round: 4, pick: 5, player: "Jaylen Waddle", team: "2 Hurlburts 1 Cup", position: "WR" },
      { round: 4, pick: 6, player: "Najee Harris", team: "Team Crook", position: "RB" },
      { round: 4, pick: 7, player: "Aaron Jones", team: "Commissioner of The Year", position: "RB" },
      { round: 4, pick: 8, player: "Mark Andrews", team: "Harbaugh's Burger Joint", position: "TE" },
      { round: 4, pick: 9, player: "Keenan Allen", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 4, pick: 10, player: "Kenneth Walker III", team: "Beats By Ray (Rice)", position: "RB" },
      { round: 5, pick: 1, player: "T.J. Hockenson", team: "Beats By Ray (Rice)", position: "TE" },
      { round: 5, pick: 2, player: "George Kittle", team: "Richmond Diamond Dogs", position: "TE" },
      { round: 5, pick: 3, player: "Jerry Jeudy", team: "Harbaugh's Burger Joint", position: "WR" },
      { round: 5, pick: 4, player: "Breece Hall", team: "Commissioner of The Year", position: "RB" },
      { round: 5, pick: 5, player: "Amari Cooper", team: "Team Crook", position: "WR" },
      { round: 5, pick: 6, player: "Lamar Jackson", team: "2 Hurlburts 1 Cup", position: "QB" },
      { round: 5, pick: 7, player: "Dameon Pierce", team: "I Like Turtles", position: "RB" },
      { round: 5, pick: 8, player: "Christian Watson", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 5, pick: 9, player: "DeAndre Hopkins", team: "Saquon these balls", position: "WR" },
      { round: 5, pick: 10, player: "Justin Fields", team: "King Beef", position: "QB" },
      { round: 6, pick: 1, player: "Darren Waller", team: "King Beef", position: "TE" },
      { round: 6, pick: 2, player: "Justin Herbert", team: "Saquon these balls", position: "QB" },
      { round: 6, pick: 3, player: "Kyle Pitts", team: "I Can't Brees \u270a\ud83c\udfff", position: "TE" },
      { round: 6, pick: 4, player: "Trevor Lawrence", team: "I Like Turtles", position: "QB" },
      { round: 6, pick: 5, player: "Chris Godwin", team: "2 Hurlburts 1 Cup", position: "WR" },
      { round: 6, pick: 6, player: "Deshaun Watson", team: "Team Crook", position: "QB" },
      { round: 6, pick: 7, player: "Diontae Johnson", team: "Commissioner of The Year", position: "WR" },
      { round: 6, pick: 8, player: "Rachaad White", team: "Harbaugh's Burger Joint", position: "RB" },
      { round: 6, pick: 9, player: "David Montgomery", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 6, pick: 10, player: "James Conner", team: "Beats By Ray (Rice)", position: "RB" },
      { round: 7, pick: 1, player: "Terry McLaurin", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 7, pick: 2, player: "Tyler Lockett", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 7, pick: 3, player: "DJ Moore", team: "Harbaugh's Burger Joint", position: "WR" },
      { round: 7, pick: 4, player: "Alexander Mattison", team: "Commissioner of The Year", position: "RB" },
      { round: 7, pick: 5, player: "Miles Sanders", team: "Team Crook", position: "RB" },
      { round: 7, pick: 6, player: "Alvin Kamara", team: "2 Hurlburts 1 Cup", position: "RB" },
      { round: 7, pick: 7, player: "Jahan Dotson", team: "I Like Turtles", position: "WR" },
      { round: 7, pick: 8, player: "Mike Evans", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 7, pick: 9, player: "Javonte Williams", team: "Saquon these balls", position: "RB" },
      { round: 7, pick: 10, player: "Mike Williams", team: "King Beef", position: "WR" },
      { round: 8, pick: 1, player: "Drake London", team: "King Beef", position: "WR" },
      { round: 8, pick: 2, player: "Dallas Goedert", team: "Saquon these balls", position: "TE" },
      { round: 8, pick: 3, player: "Cam Akers", team: "I Can't Brees \u270a\ud83c\udfff", position: "RB" },
      { round: 8, pick: 4, player: "Pat Freiermuth", team: "I Like Turtles", position: "TE" },
      { round: 8, pick: 5, player: "Marquise Brown", team: "2 Hurlburts 1 Cup", position: "WR" },
      { round: 8, pick: 6, player: "Brandon Aiyuk", team: "Team Crook", position: "WR" },
      { round: 8, pick: 7, player: "Evan Engram", team: "Commissioner of The Year", position: "TE" },
      { round: 8, pick: 8, player: "James Cook", team: "Harbaugh's Burger Joint", position: "RB" },
      { round: 8, pick: 9, player: "Jamaal Williams", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 8, pick: 10, player: "Christian Kirk", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 9, pick: 1, player: "Dalvin Cook", team: "Beats By Ray (Rice)", position: "RB" },
      { round: 9, pick: 2, player: "Michael Pittman Jr.", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 9, pick: 3, player: "Isiah Pacheco", team: "Harbaugh's Burger Joint", position: "RB" },
      { round: 9, pick: 4, player: "Dak Prescott", team: "Commissioner of The Year", position: "QB" },
      { round: 9, pick: 5, player: "Michael Thomas", team: "Team Crook", position: "WR" },
      { round: 9, pick: 6, player: "Jaxon Smith-Njigba", team: "2 Hurlburts 1 Cup", position: "WR" },
      { round: 9, pick: 7, player: "Khalil Herbert", team: "I Like Turtles", position: "RB" },
      { round: 9, pick: 8, player: "David Njoku", team: "I Can't Brees \u270a\ud83c\udfff", position: "TE" },
      { round: 9, pick: 9, player: "Brandin Cooks", team: "Saquon these balls", position: "WR" },
      { round: 9, pick: 10, player: "AJ Dillon", team: "King Beef", position: "RB" },
      { round: 10, pick: 1, player: "George Pickens", team: "King Beef", position: "WR" },
      { round: 10, pick: 2, player: "J.K. Dobbins", team: "Saquon these balls", position: "RB" },
      { round: 10, pick: 3, player: "Courtland Sutton", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 10, pick: 4, player: "JuJu Smith-Schuster", team: "I Like Turtles", position: "WR" },
      { round: 10, pick: 5, player: "49ers D/ST", team: "2 Hurlburts 1 Cup", position: "DST" },
      { round: 10, pick: 6, player: "Samaje Perine", team: "Team Crook", position: "RB" },
      { round: 10, pick: 7, player: "Bills D/ST", team: "Commissioner of The Year", position: "DST" },
      { round: 10, pick: 8, player: "Skyy Moore", team: "Harbaugh's Burger Joint", position: "WR" },
      { round: 10, pick: 9, player: "Cole Kmet", team: "Richmond Diamond Dogs", position: "TE" },
      { round: 10, pick: 10, player: "Justin Tucker", team: "Beats By Ray (Rice)", position: "K" },
      { round: 11, pick: 1, player: "Steelers D/ST", team: "Beats By Ray (Rice)", position: "DST" },
      { round: 11, pick: 2, player: "Daniel Carlson", team: "Richmond Diamond Dogs", position: "K" },
      { round: 11, pick: 3, player: "D'Andre Swift", team: "Harbaugh's Burger Joint", position: "RB" },
      { round: 11, pick: 4, player: "DJ Chark Jr.", team: "Commissioner of The Year", position: "WR" },
      { round: 11, pick: 5, player: "Saints D/ST", team: "Team Crook", position: "DST" },
      { round: 11, pick: 6, player: "Brian Robinson Jr.", team: "2 Hurlburts 1 Cup", position: "RB" },
      { round: 11, pick: 7, player: "Eagles D/ST", team: "I Like Turtles", position: "DST" },
      { round: 11, pick: 8, player: "Evan McPherson", team: "I Can't Brees \u270a\ud83c\udfff", position: "K" },
      { round: 11, pick: 9, player: "Harrison Butker", team: "Saquon these balls", position: "K" },
      { round: 11, pick: 10, player: "Graham Gano", team: "King Beef", position: "K" },
      { round: 12, pick: 1, player: "Dolphins D/ST", team: "King Beef", position: "DST" },
      { round: 12, pick: 2, player: "Cowboys D/ST", team: "Saquon these balls", position: "DST" },
      { round: 12, pick: 3, player: "Browns D/ST", team: "I Can't Brees \u270a\ud83c\udfff", position: "DST" },
      { round: 12, pick: 4, player: "Younghoe Koo", team: "I Like Turtles", position: "K" },
      { round: 12, pick: 5, player: "Zach Ertz", team: "2 Hurlburts 1 Cup", position: "TE" },
      { round: 12, pick: 6, player: "Brett Maher", team: "Team Crook", position: "K" },
      { round: 12, pick: 7, player: "Treylon Burks", team: "Commissioner of The Year", position: "WR" },
      { round: 12, pick: 8, player: "Zay Flowers", team: "Harbaugh's Burger Joint", position: "WR" },
      { round: 12, pick: 9, player: "Patriots D/ST", team: "Richmond Diamond Dogs", position: "DST" },
      { round: 12, pick: 10, player: "Tyler Higbee", team: "Beats By Ray (Rice)", position: "TE" },
      { round: 13, pick: 1, player: "Jakobi Meyers", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 13, pick: 2, player: "Jerick McKinnon", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 13, pick: 3, player: "Jordan Addison", team: "Harbaugh's Burger Joint", position: "WR" },
      { round: 13, pick: 4, player: "Kirk Cousins", team: "Commissioner of The Year", position: "QB" },
      { round: 13, pick: 5, player: "Rashaad Penny", team: "Team Crook", position: "RB" },
      { round: 13, pick: 6, player: "Anthony Richardson", team: "2 Hurlburts 1 Cup", position: "QB" },
      { round: 13, pick: 7, player: "Alec Pierce", team: "I Like Turtles", position: "WR" },
      { round: 13, pick: 8, player: "Geno Smith", team: "I Can't Brees \u270a\ud83c\udfff", position: "QB" },
      { round: 13, pick: 9, player: "Odell Beckham Jr.", team: "Saquon these balls", position: "WR" },
      { round: 13, pick: 10, player: "Aaron Rodgers", team: "King Beef", position: "QB" },
      { round: 14, pick: 1, player: "Antonio Gibson", team: "King Beef", position: "RB" },
      { round: 14, pick: 2, player: "Daniel Jones", team: "Saquon these balls", position: "QB" },
      { round: 14, pick: 3, player: "Rondale Moore", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 14, pick: 4, player: "Roschon Johnson", team: "I Like Turtles", position: "RB" },
      { round: 14, pick: 5, player: "Elijah Mitchell", team: "2 Hurlburts 1 Cup", position: "RB" },
      { round: 14, pick: 6, player: "Nico Collins", team: "Team Crook", position: "WR" },
      { round: 14, pick: 7, player: "Ezekiel Elliott", team: "Commissioner of The Year", position: "RB" },
      { round: 14, pick: 8, player: "Zach Charbonnet", team: "Harbaugh's Burger Joint", position: "RB" },
      { round: 14, pick: 9, player: "Jared Goff", team: "Richmond Diamond Dogs", position: "QB" },
      { round: 14, pick: 10, player: "Jeff Wilson Jr.", team: "Beats By Ray (Rice)", position: "RB" },
      { round: 15, pick: 1, player: "Russell Wilson", team: "Beats By Ray (Rice)", position: "QB" },
      { round: 15, pick: 2, player: "Raheem Mostert", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 15, pick: 3, player: "Jason Myers", team: "Harbaugh's Burger Joint", position: "K" },
      { round: 15, pick: 4, player: "Tyler Allgeier", team: "Commissioner of The Year", position: "RB" },
      { round: 15, pick: 5, player: "Matthew Stafford", team: "Team Crook", position: "QB" },
      { round: 15, pick: 6, player: "Chigoziem Okonkwo", team: "2 Hurlburts 1 Cup", position: "TE" },
      { round: 15, pick: 7, player: "Gabe Davis", team: "I Like Turtles", position: "WR" },
      { round: 15, pick: 8, player: "Devin Singletary", team: "I Can't Brees \u270a\ud83c\udfff", position: "RB" },
      { round: 15, pick: 9, player: "Jaylen Warren", team: "Saquon these balls", position: "RB" },
      { round: 15, pick: 10, player: "Dalton Schultz", team: "King Beef", position: "TE" },
      { round: 16, pick: 1, player: "Darnell Mooney", team: "King Beef", position: "WR" },
      { round: 16, pick: 2, player: "Quentin Johnston", team: "Saquon these balls", position: "WR" },
      { round: 16, pick: 3, player: "Michael Gallup", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 16, pick: 4, player: "Tua Tagovailoa", team: "I Like Turtles", position: "QB" },
      { round: 16, pick: 5, player: "Greg Zuerlein", team: "2 Hurlburts 1 Cup", position: "K" },
      { round: 16, pick: 6, player: "Adam Thielen", team: "Team Crook", position: "WR" },
      { round: 16, pick: 7, player: "Tyler Bass", team: "Commissioner of The Year", position: "K" },
      { round: 16, pick: 8, player: "Ravens D/ST", team: "Harbaugh's Burger Joint", position: "DST" },
      { round: 16, pick: 9, player: "Allen Lazard", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 16, pick: 10, player: "Tyler Boyd", team: "Beats By Ray (Rice)", position: "WR" },
    ],
  },
  2022: {
    owners: {
      "Kelce You Later": "Jack Callahan",
      "Team Crook": "Zach Crook",
      "King Beef": "Evan Lamb",
      "Beats By Ray (Rice)": "Austin Gauss",
      "I think we done": "Benjamin Schon",
      "Commissioner of The Year": "Jon Hurlburt",
      "Richmond Diamond Dogs": "Zack Rollis",
      "2 Hurlburts 1 Cup": "Brent Hurlburt",
      "I Can't Brees \u270a\ud83c\udfff": "Adam Schon",
      "What R U Doing Step Burrow": "Jacob Ayriss",
    },
    picks: [
      { round: 1, pick: 1, player: "Jonathan Taylor", team: "Kelce You Later", position: "RB" },
      { round: 1, pick: 2, player: "Christian McCaffrey", team: "Team Crook", position: "RB" },
      { round: 1, pick: 3, player: "Derrick Henry", team: "King Beef", position: "RB" },
      { round: 1, pick: 4, player: "Cooper Kupp", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 1, pick: 5, player: "Justin Jefferson", team: "I think we done", position: "WR" },
      { round: 1, pick: 6, player: "Austin Ekeler", team: "Commissioner of The Year", position: "RB" },
      { round: 1, pick: 7, player: "Ja'Marr Chase", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 1, pick: 8, player: "Najee Harris", team: "2 Hurlburts 1 Cup", position: "RB" },
      { round: 1, pick: 9, player: "Alvin Kamara", team: "I Can't Brees \u270a\ud83c\udfff", position: "RB" },
      { round: 1, pick: 10, player: "Dalvin Cook", team: "What R U Doing Step Burrow", position: "RB" },
      { round: 2, pick: 1, player: "D'Andre Swift", team: "What R U Doing Step Burrow", position: "RB" },
      { round: 2, pick: 2, player: "Deebo Samuel", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 2, pick: 3, player: "Stefon Diggs", team: "2 Hurlburts 1 Cup", position: "WR" },
      { round: 2, pick: 4, player: "Joe Mixon", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 2, pick: 5, player: "CeeDee Lamb", team: "Commissioner of The Year", position: "WR" },
      { round: 2, pick: 6, player: "Davante Adams", team: "I think we done", position: "WR" },
      { round: 2, pick: 7, player: "Tyreek Hill", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 2, pick: 8, player: "Tee Higgins", team: "King Beef", position: "WR" },
      { round: 2, pick: 9, player: "Leonard Fournette", team: "Team Crook", position: "RB" },
      { round: 2, pick: 10, player: "Travis Kelce", team: "Kelce You Later", position: "TE" },
      { round: 3, pick: 1, player: "Aaron Jones", team: "Kelce You Later", position: "RB" },
      { round: 3, pick: 2, player: "Mark Andrews", team: "Team Crook", position: "TE" },
      { round: 3, pick: 3, player: "Javonte Williams", team: "King Beef", position: "RB" },
      { round: 3, pick: 4, player: "James Conner", team: "Beats By Ray (Rice)", position: "RB" },
      { round: 3, pick: 5, player: "Nick Chubb", team: "I think we done", position: "RB" },
      { round: 3, pick: 6, player: "Michael Pittman Jr.", team: "Commissioner of The Year", position: "WR" },
      { round: 3, pick: 7, player: "Josh Allen", team: "Richmond Diamond Dogs", position: "QB" },
      { round: 3, pick: 8, player: "Saquon Barkley", team: "2 Hurlburts 1 Cup", position: "RB" },
      { round: 3, pick: 9, player: "Ezekiel Elliott", team: "I Can't Brees \u270a\ud83c\udfff", position: "RB" },
      { round: 3, pick: 10, player: "Keenan Allen", team: "What R U Doing Step Burrow", position: "WR" },
      { round: 4, pick: 1, player: "Mike Evans", team: "What R U Doing Step Burrow", position: "WR" },
      { round: 4, pick: 2, player: "Lamar Jackson", team: "I Can't Brees \u270a\ud83c\udfff", position: "QB" },
      { round: 4, pick: 3, player: "A.J. Brown", team: "2 Hurlburts 1 Cup", position: "WR" },
      { round: 4, pick: 4, player: "Cam Akers", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 4, pick: 5, player: "DJ Moore", team: "Commissioner of The Year", position: "WR" },
      { round: 4, pick: 6, player: "Justin Herbert", team: "I think we done", position: "QB" },
      { round: 4, pick: 7, player: "Terry McLaurin", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 4, pick: 8, player: "Mike Williams", team: "King Beef", position: "WR" },
      { round: 4, pick: 9, player: "Kyle Pitts", team: "Team Crook", position: "TE" },
      { round: 4, pick: 10, player: "Diontae Johnson", team: "Kelce You Later", position: "WR" },
      { round: 5, pick: 1, player: "Patrick Mahomes", team: "Kelce You Later", position: "QB" },
      { round: 5, pick: 2, player: "Courtland Sutton", team: "Team Crook", position: "WR" },
      { round: 5, pick: 3, player: "Darren Waller", team: "King Beef", position: "TE" },
      { round: 5, pick: 4, player: "David Montgomery", team: "Beats By Ray (Rice)", position: "RB" },
      { round: 5, pick: 5, player: "Amon-Ra St. Brown", team: "I think we done", position: "WR" },
      { round: 5, pick: 6, player: "J.K. Dobbins", team: "Commissioner of The Year", position: "RB" },
      { round: 5, pick: 7, player: "DK Metcalf", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 5, pick: 8, player: "Jaylen Waddle", team: "2 Hurlburts 1 Cup", position: "WR" },
      { round: 5, pick: 9, player: "Brandin Cooks", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 5, pick: 10, player: "Marquise Brown", team: "What R U Doing Step Burrow", position: "WR" },
      { round: 6, pick: 1, player: "George Kittle", team: "What R U Doing Step Burrow", position: "TE" },
      { round: 6, pick: 2, player: "Dalton Schultz", team: "I Can't Brees \u270a\ud83c\udfff", position: "TE" },
      { round: 6, pick: 3, player: "Breece Hall", team: "2 Hurlburts 1 Cup", position: "RB" },
      { round: 6, pick: 4, player: "T.J. Hockenson", team: "Richmond Diamond Dogs", position: "TE" },
      { round: 6, pick: 5, player: "Travis Etienne Jr.", team: "Commissioner of The Year", position: "RB" },
      { round: 6, pick: 6, player: "Allen Robinson II", team: "I think we done", position: "WR" },
      { round: 6, pick: 7, player: "Jerry Jeudy", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 6, pick: 8, player: "Gabe Davis", team: "King Beef", position: "WR" },
      { round: 6, pick: 9, player: "Michael Thomas", team: "Team Crook", position: "WR" },
      { round: 6, pick: 10, player: "Chris Godwin", team: "Kelce You Later", position: "WR" },
      { round: 7, pick: 1, player: "Darnell Mooney", team: "Kelce You Later", position: "WR" },
      { round: 7, pick: 2, player: "Amari Cooper", team: "Team Crook", position: "WR" },
      { round: 7, pick: 3, player: "Antonio Gibson", team: "King Beef", position: "RB" },
      { round: 7, pick: 4, player: "Kyler Murray", team: "Beats By Ray (Rice)", position: "QB" },
      { round: 7, pick: 5, player: "Dameon Pierce", team: "I think we done", position: "RB" },
      { round: 7, pick: 6, player: "JuJu Smith-Schuster", team: "Commissioner of The Year", position: "WR" },
      { round: 7, pick: 7, player: "Josh Jacobs", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 7, pick: 8, player: "Elijah Mitchell", team: "2 Hurlburts 1 Cup", position: "RB" },
      { round: 7, pick: 9, player: "Hunter Renfrow", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 7, pick: 10, player: "Rashod Bateman", team: "What R U Doing Step Burrow", position: "WR" },
      { round: 8, pick: 1, player: "Tony Pollard", team: "What R U Doing Step Burrow", position: "RB" },
      { round: 8, pick: 2, player: "Bills D/ST", team: "I Can't Brees \u270a\ud83c\udfff", position: "DST" },
      { round: 8, pick: 3, player: "Zach Ertz", team: "2 Hurlburts 1 Cup", position: "TE" },
      { round: 8, pick: 4, player: "Adam Thielen", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 8, pick: 5, player: "Dallas Goedert", team: "Commissioner of The Year", position: "TE" },
      { round: 8, pick: 6, player: "Dawson Knox", team: "I think we done", position: "TE" },
      { round: 8, pick: 7, player: "Miles Sanders", team: "Beats By Ray (Rice)", position: "RB" },
      { round: 8, pick: 8, player: "Elijah Moore", team: "King Beef", position: "WR" },
      { round: 8, pick: 9, player: "AJ Dillon", team: "Team Crook", position: "RB" },
      { round: 8, pick: 10, player: "Devin Singletary", team: "Kelce You Later", position: "RB" },
      { round: 9, pick: 1, player: "Justin Tucker", team: "Kelce You Later", position: "K" },
      { round: 9, pick: 2, player: "Jalen Hurts", team: "Team Crook", position: "QB" },
      { round: 9, pick: 3, player: "Dak Prescott", team: "King Beef", position: "QB" },
      { round: 9, pick: 4, player: "Drake London", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 9, pick: 5, player: "Brian Robinson Jr.", team: "I think we done", position: "RB" },
      { round: 9, pick: 6, player: "Tom Brady", team: "Commissioner of The Year", position: "QB" },
      { round: 9, pick: 7, player: "Matthew Stafford", team: "Richmond Diamond Dogs", position: "QB" },
      { round: 9, pick: 8, player: "Russell Wilson", team: "2 Hurlburts 1 Cup", position: "QB" },
      { round: 9, pick: 9, player: "Clyde Edwards-Helaire", team: "I Can't Brees \u270a\ud83c\udfff", position: "RB" },
      { round: 9, pick: 10, player: "Joe Burrow", team: "What R U Doing Step Burrow", position: "QB" },
      { round: 10, pick: 1, player: "Christian Kirk", team: "What R U Doing Step Burrow", position: "WR" },
      { round: 10, pick: 2, player: "Tyler Lockett", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 10, pick: 3, player: "Kenneth Walker III", team: "2 Hurlburts 1 Cup", position: "RB" },
      { round: 10, pick: 4, player: "Chase Edmonds", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 10, pick: 5, player: "James Robinson", team: "Commissioner of The Year", position: "RB" },
      { round: 10, pick: 6, player: "Skyy Moore", team: "I think we done", position: "WR" },
      { round: 10, pick: 7, player: "DeVonta Smith", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 10, pick: 8, player: "Rhamondre Stevenson", team: "King Beef", position: "RB" },
      { round: 10, pick: 9, player: "Kareem Hunt", team: "Team Crook", position: "RB" },
      { round: 10, pick: 10, player: "Damien Harris", team: "Kelce You Later", position: "RB" },
      { round: 11, pick: 1, player: "Aaron Rodgers", team: "Kelce You Later", position: "QB" },
      { round: 11, pick: 2, player: "DeAndre Hopkins", team: "Team Crook", position: "WR" },
      { round: 11, pick: 3, player: "Brandon Aiyuk", team: "King Beef", position: "WR" },
      { round: 11, pick: 4, player: "Kadarius Toney", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 11, pick: 5, player: "Tyler Allgeier", team: "I think we done", position: "RB" },
      { round: 11, pick: 6, player: "Rashaad Penny", team: "Commissioner of The Year", position: "RB" },
      { round: 11, pick: 7, player: "Saints D/ST", team: "Richmond Diamond Dogs", position: "DST" },
      { round: 11, pick: 8, player: "Allen Lazard", team: "2 Hurlburts 1 Cup", position: "WR" },
      { round: 11, pick: 9, player: "Trey Lance", team: "I Can't Brees \u270a\ud83c\udfff", position: "QB" },
      { round: 11, pick: 10, player: "Chase Claypool", team: "What R U Doing Step Burrow", position: "WR" },
      { round: 12, pick: 1, player: "Jakobi Meyers", team: "What R U Doing Step Burrow", position: "WR" },
      { round: 12, pick: 2, player: "Michael Carter", team: "I Can't Brees \u270a\ud83c\udfff", position: "RB" },
      { round: 12, pick: 3, player: "Cordarrelle Patterson", team: "2 Hurlburts 1 Cup", position: "RB" },
      { round: 12, pick: 4, player: "Robert Woods", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 12, pick: 5, player: "Pat Freiermuth", team: "Commissioner of The Year", position: "TE" },
      { round: 12, pick: 6, player: "George Pickens", team: "I think we done", position: "WR" },
      { round: 12, pick: 7, player: "Mike Gesicki", team: "Beats By Ray (Rice)", position: "TE" },
      { round: 12, pick: 8, player: "Kirk Cousins", team: "King Beef", position: "QB" },
      { round: 12, pick: 9, player: "Garrett Wilson", team: "Team Crook", position: "WR" },
      { round: 12, pick: 10, player: "Chris Olave", team: "Kelce You Later", position: "WR" },
      { round: 13, pick: 1, player: "Packers D/ST", team: "Kelce You Later", position: "DST" },
      { round: 13, pick: 2, player: "Melvin Gordon III", team: "Team Crook", position: "RB" },
      { round: 13, pick: 3, player: "Ravens D/ST", team: "King Beef", position: "DST" },
      { round: 13, pick: 4, player: "James Cook", team: "Beats By Ray (Rice)", position: "RB" },
      { round: 13, pick: 5, player: "Colts D/ST", team: "I think we done", position: "DST" },
      { round: 13, pick: 6, player: "Buccaneers D/ST", team: "Commissioner of The Year", position: "DST" },
      { round: 13, pick: 7, player: "Younghoe Koo", team: "Richmond Diamond Dogs", position: "K" },
      { round: 13, pick: 8, player: "Treylon Burks", team: "2 Hurlburts 1 Cup", position: "WR" },
      { round: 13, pick: 9, player: "Cole Kmet", team: "I Can't Brees \u270a\ud83c\udfff", position: "TE" },
      { round: 13, pick: 10, player: "Tyler Boyd", team: "What R U Doing Step Burrow", position: "WR" },
      { round: 14, pick: 1, player: "49ers D/ST", team: "What R U Doing Step Burrow", position: "DST" },
      { round: 14, pick: 2, player: "Evan McPherson", team: "I Can't Brees \u270a\ud83c\udfff", position: "K" },
      { round: 14, pick: 3, player: "Alexander Mattison", team: "2 Hurlburts 1 Cup", position: "RB" },
      { round: 14, pick: 4, player: "Marquez Valdes-Scantling", team: "Richmond Diamond Dogs", position: "WR" },
      { round: 14, pick: 5, player: "Russell Gage", team: "Commissioner of The Year", position: "WR" },
      { round: 14, pick: 6, player: "Nyheim Hines", team: "I think we done", position: "RB" },
      { round: 14, pick: 7, player: "Kenny Golladay", team: "Beats By Ray (Rice)", position: "WR" },
      { round: 14, pick: 8, player: "DJ Chark", team: "King Beef", position: "WR" },
      { round: 14, pick: 9, player: "Cowboys D/ST", team: "Team Crook", position: "DST" },
      { round: 14, pick: 10, player: "Hunter Henry", team: "Kelce You Later", position: "TE" },
      { round: 15, pick: 1, player: "Jarvis Landry", team: "Kelce You Later", position: "WR" },
      { round: 15, pick: 2, player: "Matt Gay", team: "Team Crook", position: "K" },
      { round: 15, pick: 3, player: "Harrison Butker", team: "King Beef", position: "K" },
      { round: 15, pick: 4, player: "Steelers D/ST", team: "Beats By Ray (Rice)", position: "DST" },
      { round: 15, pick: 5, player: "Tyler Bass", team: "I think we done", position: "K" },
      { round: 15, pick: 6, player: "Nick Folk", team: "Commissioner of The Year", position: "K" },
      { round: 15, pick: 7, player: "J.D. McKissic", team: "Richmond Diamond Dogs", position: "RB" },
      { round: 15, pick: 8, player: "Daniel Carlson", team: "2 Hurlburts 1 Cup", position: "K" },
      { round: 15, pick: 9, player: "Julio Jones", team: "I Can't Brees \u270a\ud83c\udfff", position: "WR" },
      { round: 15, pick: 10, player: "Brandon McManus", team: "What R U Doing Step Burrow", position: "K" },
      { round: 16, pick: 1, player: "Raheem Mostert", team: "What R U Doing Step Burrow", position: "RB" },
      { round: 16, pick: 2, player: "Graham Gano", team: "I Can't Brees \u270a\ud83c\udfff", position: "K" },
      { round: 16, pick: 3, player: "Commanders D/ST", team: "2 Hurlburts 1 Cup", position: "DST" },
      { round: 16, pick: 4, player: "Albert Okwuegbunam", team: "Richmond Diamond Dogs", position: "TE" },
      { round: 16, pick: 5, player: "Derek Carr", team: "Commissioner of The Year", position: "QB" },
      { round: 16, pick: 6, player: "David Njoku", team: "I think we done", position: "TE" },
      { round: 16, pick: 7, player: "Matt Prater", team: "Beats By Ray (Rice)", position: "K" },
      { round: 16, pick: 8, player: "Tyler Higbee", team: "King Beef", position: "TE" },
      { round: 16, pick: 9, player: "Jahan Dotson", team: "Team Crook", position: "WR" },
      { round: 16, pick: 10, player: "Jamaal Williams", team: "Kelce You Later", position: "RB" },
    ],
  },
  2021: {
    owners: {
      "Gore winning me a championship": "Bobby Mowry",
      "King Beef": "Evan Lamb",
      "Your Mom\u2019s Haus F Shit Up": "Zack Rollis",
      "The Delegate From 4SKN": "Jon Hurlburt",
      "The Real Slim Brady": "Jacob Ayriss",
      "Nick Foles SZN Champ": "Benjamin Schon",
      "Save The Bees": "Zach Crook",
      "I Believe": "Jack Callahan",
    },
    picks: [
      { round: 1, pick: 1, player: "Christian McCaffrey", team: "Gore winning me a championship", position: "RB" },
      { round: 1, pick: 2, player: "Alvin Kamara", team: "King Beef", position: "RB" },
      { round: 1, pick: 3, player: "Dalvin Cook", team: "Your Mom\u2019s Haus F Shit Up", position: "RB" },
      { round: 1, pick: 4, player: "Derrick Henry", team: "The Delegate From 4SKN", position: "RB" },
      { round: 1, pick: 5, player: "Ezekiel Elliott", team: "The Real Slim Brady", position: "RB" },
      { round: 1, pick: 6, player: "Travis Kelce", team: "Nick Foles SZN Champ", position: "TE" },
      { round: 1, pick: 7, player: "Davante Adams", team: "Save The Bees", position: "WR" },
      { round: 1, pick: 8, player: "Saquon Barkley", team: "I Believe", position: "RB" },
      { round: 2, pick: 1, player: "Austin Ekeler", team: "I Believe", position: "RB" },
      { round: 2, pick: 2, player: "Jonathan Taylor", team: "Save The Bees", position: "RB" },
      { round: 2, pick: 3, player: "Nick Chubb", team: "Nick Foles SZN Champ", position: "RB" },
      { round: 2, pick: 4, player: "Antonio Gibson", team: "The Real Slim Brady", position: "RB" },
      { round: 2, pick: 5, player: "Aaron Jones", team: "The Delegate From 4SKN", position: "RB" },
      { round: 2, pick: 6, player: "Tyreek Hill", team: "Your Mom\u2019s Haus F Shit Up", position: "WR" },
      { round: 2, pick: 7, player: "Najee Harris", team: "King Beef", position: "RB" },
      { round: 2, pick: 8, player: "Stefon Diggs", team: "Gore winning me a championship", position: "WR" },
      { round: 3, pick: 1, player: "DeAndre Hopkins", team: "Gore winning me a championship", position: "WR" },
      { round: 3, pick: 2, player: "Calvin Ridley", team: "King Beef", position: "WR" },
      { round: 3, pick: 3, player: "DK Metcalf", team: "Your Mom\u2019s Haus F Shit Up", position: "WR" },
      { round: 3, pick: 4, player: "Justin Jefferson", team: "The Delegate From 4SKN", position: "WR" },
      { round: 3, pick: 5, player: "Terry McLaurin", team: "The Real Slim Brady", position: "WR" },
      { round: 3, pick: 6, player: "Keenan Allen", team: "Nick Foles SZN Champ", position: "WR" },
      { round: 3, pick: 7, player: "Clyde Edwards-Helaire", team: "Save The Bees", position: "RB" },
      { round: 3, pick: 8, player: "Darren Waller", team: "I Believe", position: "TE" },
      { round: 4, pick: 1, player: "Joe Mixon", team: "I Believe", position: "RB" },
      { round: 4, pick: 2, player: "George Kittle", team: "Save The Bees", position: "TE" },
      { round: 4, pick: 3, player: "James Robinson", team: "Nick Foles SZN Champ", position: "RB" },
      { round: 4, pick: 4, player: "Allen Robinson II", team: "The Real Slim Brady", position: "WR" },
      { round: 4, pick: 5, player: "A.J. Brown", team: "The Delegate From 4SKN", position: "WR" },
      { round: 4, pick: 6, player: "CeeDee Lamb", team: "Your Mom\u2019s Haus F Shit Up", position: "WR" },
      { round: 4, pick: 7, player: "Mike Evans", team: "King Beef", position: "WR" },
      { round: 4, pick: 8, player: "David Montgomery", team: "Gore winning me a championship", position: "RB" },
      { round: 5, pick: 1, player: "Miles Sanders", team: "Gore winning me a championship", position: "RB" },
      { round: 5, pick: 2, player: "Chris Carson", team: "King Beef", position: "RB" },
      { round: 5, pick: 3, player: "D'Andre Swift", team: "Your Mom\u2019s Haus F Shit Up", position: "RB" },
      { round: 5, pick: 4, player: "Robert Woods", team: "The Delegate From 4SKN", position: "WR" },
      { round: 5, pick: 5, player: "J.K. Dobbins", team: "The Real Slim Brady", position: "RB" },
      { round: 5, pick: 6, player: "Josh Allen", team: "Nick Foles SZN Champ", position: "QB" },
      { round: 5, pick: 7, player: "Amari Cooper", team: "Save The Bees", position: "WR" },
      { round: 5, pick: 8, player: "Adam Thielen", team: "I Believe", position: "WR" },
      { round: 6, pick: 1, player: "Chris Godwin", team: "I Believe", position: "WR" },
      { round: 6, pick: 2, player: "Patrick Mahomes", team: "Save The Bees", position: "QB" },
      { round: 6, pick: 3, player: "Cooper Kupp", team: "Nick Foles SZN Champ", position: "WR" },
      { round: 6, pick: 4, player: "Diontae Johnson", team: "The Real Slim Brady", position: "WR" },
      { round: 6, pick: 5, player: "Josh Jacobs", team: "The Delegate From 4SKN", position: "RB" },
      { round: 6, pick: 6, player: "Tyler Lockett", team: "Your Mom\u2019s Haus F Shit Up", position: "WR" },
      { round: 6, pick: 7, player: "Kyler Murray", team: "King Beef", position: "QB" },
      { round: 6, pick: 8, player: "Julio Jones", team: "Gore winning me a championship", position: "WR" },
      { round: 7, pick: 1, player: "DJ Moore", team: "Gore winning me a championship", position: "WR" },
      { round: 7, pick: 2, player: "Myles Gaskin", team: "King Beef", position: "RB" },
      { round: 7, pick: 3, player: "Brandon Aiyuk", team: "Your Mom\u2019s Haus F Shit Up", position: "WR" },
      { round: 7, pick: 4, player: "Kareem Hunt", team: "The Delegate From 4SKN", position: "RB" },
      { round: 7, pick: 5, player: "Mark Andrews", team: "The Real Slim Brady", position: "TE" },
      { round: 7, pick: 6, player: "Trey Sermon", team: "Nick Foles SZN Champ", position: "RB" },
      { round: 7, pick: 7, player: "Chase Edmonds", team: "Save The Bees", position: "RB" },
      { round: 7, pick: 8, player: "Tom Brady", team: "I Believe", position: "QB" },
      { round: 8, pick: 1, player: "Tee Higgins", team: "I Believe", position: "WR" },
      { round: 8, pick: 2, player: "Robby Anderson", team: "Save The Bees", position: "WR" },
      { round: 8, pick: 3, player: "Jerry Jeudy", team: "Nick Foles SZN Champ", position: "WR" },
      { round: 8, pick: 4, player: "Odell Beckham Jr.", team: "The Real Slim Brady", position: "WR" },
      { round: 8, pick: 5, player: "Kenny Golladay", team: "The Delegate From 4SKN", position: "WR" },
      { round: 8, pick: 6, player: "T.J. Hockenson", team: "Your Mom\u2019s Haus F Shit Up", position: "TE" },
      { round: 8, pick: 7, player: "William Fuller V", team: "King Beef", position: "WR" },
      { round: 8, pick: 8, player: "Kyle Pitts", team: "Gore winning me a championship", position: "TE" },
      { round: 9, pick: 1, player: "Javonte Williams", team: "Gore winning me a championship", position: "RB" },
      { round: 9, pick: 2, player: "Noah Fant", team: "King Beef", position: "TE" },
      { round: 9, pick: 3, player: "Dak Prescott", team: "Your Mom\u2019s Haus F Shit Up", position: "QB" },
      { round: 9, pick: 4, player: "Logan Thomas", team: "The Delegate From 4SKN", position: "TE" },
      { round: 9, pick: 5, player: "Aaron Rodgers", team: "The Real Slim Brady", position: "QB" },
      { round: 9, pick: 6, player: "Sony Michel", team: "Nick Foles SZN Champ", position: "RB" },
      { round: 9, pick: 7, player: "Ja'Marr Chase", team: "Save The Bees", position: "WR" },
      { round: 9, pick: 8, player: "JuJu Smith-Schuster", team: "I Believe", position: "WR" },
      { round: 10, pick: 1, player: "Mike Davis", team: "I Believe", position: "RB" },
      { round: 10, pick: 2, player: "Damien Harris", team: "Save The Bees", position: "RB" },
      { round: 10, pick: 3, player: "Tyler Boyd", team: "Nick Foles SZN Champ", position: "WR" },
      { round: 10, pick: 4, player: "Courtland Sutton", team: "The Real Slim Brady", position: "WR" },
      { round: 10, pick: 5, player: "Michael Thomas", team: "The Delegate From 4SKN", position: "WR" },
      { round: 10, pick: 6, player: "Chase Claypool", team: "Your Mom\u2019s Haus F Shit Up", position: "WR" },
      { round: 10, pick: 7, player: "Kenyan Drake", team: "King Beef", position: "RB" },
      { round: 10, pick: 8, player: "Lamar Jackson", team: "Gore winning me a championship", position: "QB" },
      { round: 11, pick: 1, player: "Brandin Cooks", team: "Gore winning me a championship", position: "WR" },
      { round: 11, pick: 2, player: "Russell Wilson", team: "King Beef", position: "QB" },
      { round: 11, pick: 3, player: "Laviska Shenault Jr.", team: "Your Mom\u2019s Haus F Shit Up", position: "WR" },
      { round: 11, pick: 4, player: "Justin Herbert", team: "The Delegate From 4SKN", position: "QB" },
      { round: 11, pick: 5, player: "Michael Gallup", team: "The Real Slim Brady", position: "WR" },
      { round: 11, pick: 6, player: "Zack Moss", team: "Nick Foles SZN Champ", position: "RB" },
      { round: 11, pick: 7, player: "Deebo Samuel", team: "Save The Bees", position: "WR" },
      { round: 11, pick: 8, player: "Matthew Stafford", team: "I Believe", position: "QB" },
      { round: 12, pick: 1, player: "Buccaneers D/ST", team: "I Believe", position: "DST" },
      { round: 12, pick: 2, player: "Ryan Tannehill", team: "Save The Bees", position: "QB" },
      { round: 12, pick: 3, player: "Leonard Fournette", team: "Nick Foles SZN Champ", position: "RB" },
      { round: 12, pick: 4, player: "DeVonta Smith", team: "The Real Slim Brady", position: "WR" },
      { round: 12, pick: 5, player: "Raheem Mostert", team: "The Delegate From 4SKN", position: "RB" },
      { round: 12, pick: 6, player: "DJ Chark Jr.", team: "Your Mom\u2019s Haus F Shit Up", position: "WR" },
      { round: 12, pick: 7, player: "Marvin Jones Jr.", team: "King Beef", position: "WR" },
      { round: 12, pick: 8, player: "Corey Davis", team: "Gore winning me a championship", position: "WR" },
      { round: 13, pick: 1, player: "Darrell Henderson Jr.", team: "Gore winning me a championship", position: "RB" },
      { round: 13, pick: 2, player: "Younghoe Koo", team: "King Beef", position: "K" },
      { round: 13, pick: 3, player: "Melvin Gordon III", team: "Your Mom\u2019s Haus F Shit Up", position: "RB" },
      { round: 13, pick: 4, player: "Bills D/ST", team: "The Delegate From 4SKN", position: "DST" },
      { round: 13, pick: 5, player: "Marquise Brown", team: "The Real Slim Brady", position: "WR" },
      { round: 13, pick: 6, player: "Jarvis Landry", team: "Nick Foles SZN Champ", position: "WR" },
      { round: 13, pick: 7, player: "Ronald Jones II", team: "Save The Bees", position: "RB" },
      { round: 13, pick: 8, player: "Nyheim Hines", team: "I Believe", position: "RB" },
      { round: 14, pick: 1, player: "Antonio Brown", team: "I Believe", position: "WR" },
      { round: 14, pick: 2, player: "Ravens D/ST", team: "Save The Bees", position: "DST" },
      { round: 14, pick: 3, player: "Commanders D/ST", team: "Nick Foles SZN Champ", position: "DST" },
      { round: 14, pick: 4, player: "Dallas Goedert", team: "The Real Slim Brady", position: "TE" },
      { round: 14, pick: 5, player: "Harrison Butker", team: "The Delegate From 4SKN", position: "K" },
      { round: 14, pick: 6, player: "AJ Dillon", team: "Your Mom\u2019s Haus F Shit Up", position: "RB" },
      { round: 14, pick: 7, player: "Steelers D/ST", team: "King Beef", position: "DST" },
      { round: 14, pick: 8, player: "Curtis Samuel", team: "Gore winning me a championship", position: "WR" },
      { round: 15, pick: 1, player: "49ers D/ST", team: "Gore winning me a championship", position: "DST" },
      { round: 15, pick: 2, player: "Mike Williams", team: "King Beef", position: "WR" },
      { round: 15, pick: 3, player: "Broncos D/ST", team: "Your Mom\u2019s Haus F Shit Up", position: "DST" },
      { round: 15, pick: 4, player: "David Johnson", team: "The Delegate From 4SKN", position: "RB" },
      { round: 15, pick: 5, player: "Patriots D/ST", team: "The Real Slim Brady", position: "DST" },
      { round: 15, pick: 6, player: "Baker Mayfield", team: "Nick Foles SZN Champ", position: "QB" },
      { round: 15, pick: 7, player: "Rams D/ST", team: "Save The Bees", position: "DST" },
      { round: 15, pick: 8, player: "Justin Tucker", team: "I Believe", position: "K" },
      { round: 16, pick: 1, player: "Browns D/ST", team: "I Believe", position: "DST" },
      { round: 16, pick: 2, player: "Graham Gano", team: "Save The Bees", position: "K" },
      { round: 16, pick: 3, player: "Brandon McManus", team: "Nick Foles SZN Champ", position: "K" },
      { round: 16, pick: 4, player: "Jason Myers", team: "The Real Slim Brady", position: "K" },
      { round: 16, pick: 5, player: "Ryan Fitzpatrick", team: "The Delegate From 4SKN", position: "QB" },
      { round: 16, pick: 6, player: "Jason Sanders", team: "Your Mom\u2019s Haus F Shit Up", position: "K" },
      { round: 16, pick: 7, player: "Jaylen Waddle", team: "King Beef", position: "WR" },
      { round: 16, pick: 8, player: "Matt Gay", team: "Gore winning me a championship", position: "K" },
    ],
  },
};
