/**
 * ================================================================
 *  HEAD_TO_HEAD — all-time record between every pair of current
 *  managers (the 12-team era, 2024-present roster of owners).
 * ================================================================
 *  Built from every regular-season and playoff matchup on record
 *  (2021-2025) between two of today's managers — games against
 *  owners who have since left the league are excluded.
 *
 *  HEAD_TO_HEAD.owners -> display order (alphabetical).
 *  HEAD_TO_HEAD.matrix[A][B] -> [A's wins vs B, A's losses vs B].
 * ================================================================
 */

const HEAD_TO_HEAD = {
  owners: ["Adam Kahler", "Adam Schon", "Austin Gauss", "Ben Schon", "Blake Beachnau", "Brent Hurlburt", "Evan Lamb", "Jack Callahan", "Jacob Ayriss", "Jon Hurlburt", "Zach Crook", "Zack Rollis"],
  matrix: {
    "Adam Kahler": {
      "Adam Schon": [1, 2],
      "Austin Gauss": [1, 1],
      "Ben Schon": [1, 1],
      "Blake Beachnau": [3, 4],
      "Brent Hurlburt": [2, 1],
      "Evan Lamb": [3, 0],
      "Jack Callahan": [2, 2],
      "Jacob Ayriss": [2, 0],
      "Jon Hurlburt": [1, 1],
      "Zach Crook": [1, 2],
      "Zack Rollis": [1, 1],
    },
    "Adam Schon": {
      "Adam Kahler": [2, 1],
      "Austin Gauss": [0, 6],
      "Ben Schon": [1, 3],
      "Blake Beachnau": [2, 1],
      "Brent Hurlburt": [5, 3],
      "Evan Lamb": [2, 4],
      "Jack Callahan": [2, 5],
      "Jacob Ayriss": [3, 3],
      "Jon Hurlburt": [2, 6],
      "Zach Crook": [2, 7],
      "Zack Rollis": [3, 5],
    },
    "Austin Gauss": {
      "Adam Kahler": [1, 1],
      "Adam Schon": [6, 0],
      "Ben Schon": [5, 4],
      "Blake Beachnau": [3, 1],
      "Brent Hurlburt": [2, 3],
      "Evan Lamb": [3, 4],
      "Jack Callahan": [2, 6],
      "Jacob Ayriss": [3, 5],
      "Jon Hurlburt": [2, 2],
      "Zach Crook": [6, 1],
      "Zack Rollis": [4, 4],
    },
    "Ben Schon": {
      "Adam Kahler": [1, 1],
      "Adam Schon": [3, 1],
      "Austin Gauss": [4, 5],
      "Blake Beachnau": [1, 1],
      "Brent Hurlburt": [4, 2],
      "Evan Lamb": [10, 2],
      "Jack Callahan": [5, 4],
      "Jacob Ayriss": [7, 3],
      "Jon Hurlburt": [2, 7],
      "Zach Crook": [6, 3],
      "Zack Rollis": [3, 6],
    },
    "Blake Beachnau": {
      "Adam Kahler": [4, 3],
      "Adam Schon": [1, 2],
      "Austin Gauss": [1, 3],
      "Ben Schon": [1, 1],
      "Brent Hurlburt": [2, 0],
      "Evan Lamb": [1, 1],
      "Jack Callahan": [1, 2],
      "Jacob Ayriss": [3, 0],
      "Jon Hurlburt": [1, 1],
      "Zach Crook": [1, 1],
      "Zack Rollis": [2, 2],
    },
    "Brent Hurlburt": {
      "Adam Kahler": [1, 2],
      "Adam Schon": [3, 5],
      "Austin Gauss": [3, 2],
      "Ben Schon": [2, 4],
      "Blake Beachnau": [0, 2],
      "Evan Lamb": [3, 6],
      "Jack Callahan": [5, 1],
      "Jacob Ayriss": [4, 4],
      "Jon Hurlburt": [3, 5],
      "Zach Crook": [3, 5],
      "Zack Rollis": [4, 1],
    },
    "Evan Lamb": {
      "Adam Kahler": [0, 3],
      "Adam Schon": [4, 2],
      "Austin Gauss": [4, 3],
      "Ben Schon": [2, 10],
      "Blake Beachnau": [1, 1],
      "Brent Hurlburt": [6, 3],
      "Jack Callahan": [2, 7],
      "Jacob Ayriss": [4, 3],
      "Jon Hurlburt": [4, 4],
      "Zach Crook": [3, 5],
      "Zack Rollis": [8, 2],
    },
    "Jack Callahan": {
      "Adam Kahler": [2, 2],
      "Adam Schon": [5, 2],
      "Austin Gauss": [6, 2],
      "Ben Schon": [4, 5],
      "Blake Beachnau": [2, 1],
      "Brent Hurlburt": [1, 5],
      "Evan Lamb": [7, 2],
      "Jacob Ayriss": [3, 6],
      "Jon Hurlburt": [7, 6],
      "Zach Crook": [4, 3],
      "Zack Rollis": [4, 3],
    },
    "Jacob Ayriss": {
      "Adam Kahler": [0, 2],
      "Adam Schon": [3, 3],
      "Austin Gauss": [5, 3],
      "Ben Schon": [3, 7],
      "Blake Beachnau": [0, 3],
      "Brent Hurlburt": [4, 4],
      "Evan Lamb": [3, 4],
      "Jack Callahan": [6, 3],
      "Jon Hurlburt": [3, 5],
      "Zach Crook": [5, 4],
      "Zack Rollis": [7, 4],
    },
    "Jon Hurlburt": {
      "Adam Kahler": [1, 1],
      "Adam Schon": [6, 2],
      "Austin Gauss": [2, 2],
      "Ben Schon": [7, 2],
      "Blake Beachnau": [1, 1],
      "Brent Hurlburt": [5, 3],
      "Evan Lamb": [4, 4],
      "Jack Callahan": [6, 7],
      "Jacob Ayriss": [5, 3],
      "Zach Crook": [7, 4],
      "Zack Rollis": [5, 4],
    },
    "Zach Crook": {
      "Adam Kahler": [2, 1],
      "Adam Schon": [7, 2],
      "Austin Gauss": [1, 6],
      "Ben Schon": [3, 6],
      "Blake Beachnau": [1, 1],
      "Brent Hurlburt": [5, 3],
      "Evan Lamb": [5, 3],
      "Jack Callahan": [3, 4],
      "Jacob Ayriss": [4, 5],
      "Jon Hurlburt": [4, 7],
      "Zack Rollis": [5, 3],
    },
    "Zack Rollis": {
      "Adam Kahler": [1, 1],
      "Adam Schon": [5, 3],
      "Austin Gauss": [4, 4],
      "Ben Schon": [6, 3],
      "Blake Beachnau": [2, 2],
      "Brent Hurlburt": [1, 4],
      "Evan Lamb": [2, 8],
      "Jack Callahan": [3, 4],
      "Jacob Ayriss": [4, 7],
      "Jon Hurlburt": [4, 5],
      "Zach Crook": [3, 5],
    },
  },
};
